root: true
env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
  - react-refresh
  - prettier
rules:
  react-refresh/only-export-components:
    - warn
    - allowConstantExport: true
  '@typescript-eslint/no-non-null-assertion':
    - off
  prettier/prettier:
    - error
  react/react-in-jsx-scope:
    - off
